### PR TITLE
update cairo/pango 0.13, sdl 1.3

### PR DESCRIPTION
**Pull request by alvare**
Couldn't build because of some cairo/pango/glib 0.12 combined with cabal issue http://lpaste.net/129986
Update cairo and pango to 0.13 along with sdl2 to 1.3
Seems to be related to #90 #87 too.

### CODE REVIEW

**Comment by alvare** [comment]
Build fails[0] because of a text issue[1], I'll need to modify the travis configuration for this since text now needs the integer-simple flag disabled and it can only be done with cabal-install.

[0] https://travis-ci.org/switchface/helm/builds/56784631
[1] https://github.com/bos/text/pull/96

**Comment by alvare** [comment]
Okay it works but with GHC 7.8, my knowledge doesn't get as far as supporting multiple versions, do as you like.

**Comment by kasbah** [comment]
Thanks for taking another look. I think we need to figure out the constraints we need to add to get a reliable build for GHC 7.6 - 7.10.

**Comment by z0w0** [comment]
Shouldn't be an issue anymore as far as I know. Please open an issue if it's still happening.

**Pull request closed without merging**
